spring:
  application:
    name: seata-business
  cloud:
    nacos:
      server-addr: 192.168.43.242:8848
      config:
        import-check:
          enabled: false
server:
  port: 11000

